// ── Kategori Lokasi ──
export const categories = [
  { id: 'flora', label: 'Flora', color: '#22c55e', emoji: '🌿' },
  { id: 'fauna', label: 'Fauna', color: '#f59e0b', emoji: '🦎' },
  { id: 'tangkap', label: 'Perikanan Tangkap', color: '#3b82f6', emoji: '🎣' },
  { id: 'budidaya', label: 'Perikanan Budidaya', color: '#8b5cf6', emoji: '🐟' },
  { id: 'pesisir', label: 'Pesisir Laut', color: '#06b6d4', emoji: '🏖️' },
];

// ── URL GeoJSON Provinsi Indonesia ──
export const PROVINCE_GEOJSON_URL =
  'https://raw.githubusercontent.com/superpikar/indonesia-geojson/master/indonesia.geojson';

// ── Data Lokasi ──
export const locations = [
  // ═══════════ FLORA ═══════════
  { id: 'flora-001', name: 'Mangrove Delta Mahakam', category: 'flora', provinsi: 'Kalimantan Timur', kabupaten: 'Kutai Kartanegara', coords: [-0.55, 117.35], luas: '110.000 Ha', status: 'Kawasan Delta', tev: 'Rp 3,2 T/thn', jumlahTitikPantau: 24, ringkasan: 'Delta mangrove terluas di Kaltim dengan keanekaragaman flora mangrove tinggi.', deskripsi: 'Delta Mahakam merupakan salah satu kawasan mangrove terluas di Kalimantan Timur. Kawasan ini memiliki peran vital sebagai penyangga ekosistem pesisir, habitat ikan, serta penyerap karbon. Terdapat berbagai jenis mangrove seperti Rhizophora apiculata, Avicennia marina, dan Sonneratia alba. Upaya konservasi dilakukan bersama masyarakat lokal untuk menjaga kelestarian kawasan.', spesies: ['Rhizophora apiculata', 'Avicennia marina', 'Sonneratia alba', 'Bruguiera gymnorrhiza'], riwayat: [{ tanggal: '2024-01-15', aktivitas: 'Survei Baseline Flora', detail: 'Identifikasi 42 spesies mangrove pada 12 plot pengamatan.' }, { tanggal: '2024-04-20', aktivitas: 'Penanaman Rehabilitasi', detail: 'Penanaman 5.000 bibit Rhizophora di area degradasi seluas 8 Ha.' }, { tanggal: '2024-08-10', aktivitas: 'Monitoring Pertumbuhan', detail: 'Tingkat kelangsungan hidup bibit mencapai 78%.' }] },
  { id: 'flora-002', name: 'Mangrove Bintuni', category: 'flora', provinsi: 'Papua Barat', kabupaten: 'Teluk Bintuni', coords: [-2.1, 133.5], luas: '228.900 Ha', status: 'Cagar Alam', tev: 'Rp 5,6 T/thn', jumlahTitikPantau: 36, ringkasan: 'Kawasan mangrove terluas di Indonesia dengan status cagar alam.', deskripsi: 'Cagar Alam Teluk Bintuni merupakan kawasan mangrove terluas di Indonesia, mencakup lebih dari 228.000 hektar. Kawasan ini menjadi habitat kritis bagi berbagai spesies endemik dan berperan penting dalam mitigasi perubahan iklim melalui penyimpanan karbon biru.', spesies: ['Rhizophora stylosa', 'Bruguiera parviflora', 'Ceriops tagal', 'Xylocarpus granatum'], riwayat: [{ tanggal: '2023-11-05', aktivitas: 'Pemetaan Cagar Alam', detail: 'Pemetaan batas dan zonasi kawasan menggunakan citra satelit.' }, { tanggal: '2024-03-12', aktivitas: 'Inventarisasi Spesies', detail: 'Ditemukan 58 spesies mangrove sejati dan ikutan.' }] },
  { id: 'flora-003', name: 'Mangrove Sembilang', category: 'flora', provinsi: 'Sumatera Selatan', kabupaten: 'Banyuasin', coords: [-2.1, 104.8], luas: '202.896 Ha', status: 'Taman Nasional', tev: 'Rp 1,8 T/thn', jumlahTitikPantau: 18, ringkasan: 'Taman nasional dengan ekosistem mangrove dan rawa gambut.', deskripsi: 'Taman Nasional Berbak-Sembilang melindungi ekosistem mangrove, hutan rawa gambut, dan hutan rawa air tawar. Kawasan ini menjadi habitat penting bagi harimau sumatera, tapir, dan berbagai spesies burung air.', spesies: ['Avicennia alba', 'Rhizophora mucronata', 'Nypa fruticans', 'Sonneratia caseolaris'], riwayat: [{ tanggal: '2024-02-18', aktivitas: 'Patroli Kawasan', detail: 'Pemantauan kondisi hutan mangrove dan identifikasi ancaman.' }] },
  { id: 'flora-004', name: 'Mangrove Segara Anakan', category: 'flora', provinsi: 'Jawa Tengah', kabupaten: 'Cilacap', coords: [-7.67, 108.85], luas: '9.200 Ha', status: 'Kawasan Konservasi', tev: 'Rp 385 M/thn', jumlahTitikPantau: 12, ringkasan: 'Laguna mangrove terbesar di Pulau Jawa dengan nilai ekologis tinggi.', deskripsi: 'Segara Anakan merupakan laguna alami yang dikelilingi hutan mangrove terbesar di Pulau Jawa. Kawasan ini mengalami sedimentasi yang signifikan namun tetap menjadi habitat penting bagi berbagai spesies ikan, udang, dan burung migran.', spesies: ['Rhizophora mucronata', 'Avicennia marina', 'Sonneratia alba'], riwayat: [{ tanggal: '2024-05-20', aktivitas: 'Rehabilitasi Mangrove', detail: 'Penanaman 10.000 bibit di area terdegradasi.' }] },
  { id: 'flora-005', name: 'Mangrove Kubu Raya', category: 'flora', provinsi: 'Kalimantan Barat', kabupaten: 'Kubu Raya', coords: [-0.3, 109.15], luas: '48.200 Ha', status: 'Hutan Lindung', tev: 'Rp 1,4 T/thn', jumlahTitikPantau: 16, ringkasan: 'Kawasan mangrove terluas di pesisir barat Kalimantan.', deskripsi: 'Hutan mangrove Kubu Raya membentang di sepanjang pesisir barat Kalimantan. Kawasan ini berfungsi sebagai penahan abrasi, habitat nursery ikan, dan penyerap karbon dalam jumlah besar.', spesies: ['Rhizophora apiculata', 'Bruguiera gymnorrhiza', 'Ceriops decandra'], riwayat: [{ tanggal: '2024-06-10', aktivitas: 'Pengukuran Karbon', detail: 'Estimasi stok karbon mencapai 245 ton C/ha.' }] },
  { id: 'flora-006', name: 'Mangrove Muara Angke', category: 'flora', provinsi: 'DKI Jakarta', kabupaten: 'Jakarta Utara', coords: [-6.1, 106.73], luas: '327 Ha', status: 'Suaka Margasatwa', tev: 'Rp 85 M/thn', jumlahTitikPantau: 8, ringkasan: 'Suaka margasatwa mangrove terakhir di Jakarta.', deskripsi: 'Suaka Margasatwa Muara Angke merupakan sisa hutan mangrove di Jakarta yang dilindungi. Meskipun luasnya terus menyusut, kawasan ini masih menjadi habitat bagi burung-burung air dan sebagai laboratorium alam bagi peneliti.', spesies: ['Avicennia marina', 'Rhizophora stylosa'], riwayat: [{ tanggal: '2024-01-22', aktivitas: 'Monitoring Burung', detail: 'Tercatat 45 spesies burung air di kawasan.' }] },
  { id: 'flora-007', name: 'Mangrove Benoa', category: 'flora', provinsi: 'Bali', kabupaten: 'Denpasar', coords: [-8.72, 115.22], luas: '1.373 Ha', status: 'Taman Hutan Raya', tev: 'Rp 195 M/thn', jumlahTitikPantau: 10, ringkasan: 'Taman hutan raya mangrove unggulan Bali untuk ekowisata.', deskripsi: 'Taman Hutan Raya Ngurah Rai di kawasan Benoa merupakan area mangrove yang telah direhabilitasi dan menjadi destinasi ekowisata unggulan di Bali. Dilengkapi dengan boardwalk dan pusat informasi.', spesies: ['Rhizophora mucronata', 'Sonneratia alba', 'Avicennia marina'], riwayat: [{ tanggal: '2024-03-05', aktivitas: 'Pemeliharaan Boardwalk', detail: 'Renovasi jalur boardwalk sepanjang 2,5 km.' }] },
  { id: 'flora-008', name: 'Mangrove Wonorejo', category: 'flora', provinsi: 'Jawa Timur', kabupaten: 'Surabaya', coords: [-7.32, 112.81], luas: '480 Ha', status: 'Ekowisata Kota', tev: 'Rp 125 M/thn', jumlahTitikPantau: 6, ringkasan: 'Kawasan ekowisata mangrove di tengah kota Surabaya.', deskripsi: 'Ekowisata Mangrove Wonorejo menjadi contoh keberhasilan rehabilitasi mangrove di area perkotaan. Pengunjung dapat menikmati jalur tracking, pengamatan burung, dan edukasi lingkungan.', spesies: ['Avicennia marina', 'Rhizophora stylosa', 'Sonneratia caseolaris'], riwayat: [{ tanggal: '2024-07-15', aktivitas: 'Festival Mangrove', detail: 'Kegiatan edukasi dan penanaman bersama masyarakat.' }] },
  { id: 'flora-009', name: 'Mangrove Langsa', category: 'flora', provinsi: 'Aceh', kabupaten: 'Kota Langsa', coords: [4.47, 97.97], luas: '8.500 Ha', status: 'Kawasan Lindung', tev: 'Rp 245 M/thn', jumlahTitikPantau: 14, ringkasan: 'Kawasan mangrove lindung di pesisir timur Aceh.', deskripsi: 'Hutan mangrove Langsa di pesisir timur Aceh menjadi kawasan lindung yang penting untuk perlindungan pantai dan habitat ikan. Telah dikembangkan sebagai destinasi ekowisata lokal.', spesies: ['Rhizophora apiculata', 'Avicennia officinalis', 'Bruguiera sexangula'], riwayat: [{ tanggal: '2024-04-08', aktivitas: 'Survei Keanekaragaman', detail: 'Identifikasi 28 spesies mangrove.' }] },
  { id: 'flora-010', name: 'Mangrove Tarakan', category: 'flora', provinsi: 'Kalimantan Utara', kabupaten: 'Kota Tarakan', coords: [3.3, 117.63], luas: '7.800 Ha', status: 'Kawasan Konservasi', tev: 'Rp 225 M/thn', jumlahTitikPantau: 10, ringkasan: 'Konservasi mangrove kota di Pulau Tarakan.', deskripsi: 'Kawasan konservasi mangrove Tarakan merupakan contoh pengelolaan mangrove berbasis kota. Mangrove di sini berfungsi sebagai penahan abrasi dan habitat udang serta kepiting.', spesies: ['Rhizophora mucronata', 'Avicennia alba', 'Sonneratia ovata'], riwayat: [{ tanggal: '2024-02-28', aktivitas: 'Penanaman Bibit', detail: 'Penanaman 3.000 bibit oleh kelompok masyarakat.' }] },
  { id: 'flora-011', name: 'Mangrove Indragiri Hilir', category: 'flora', provinsi: 'Riau', kabupaten: 'Indragiri Hilir', coords: [0.35, 103.25], luas: '25.400 Ha', status: 'Hutan Produksi', tev: 'Rp 680 M/thn', jumlahTitikPantau: 20, ringkasan: 'Kawasan mangrove produktif di delta Sungai Indragiri.', deskripsi: 'Kawasan mangrove di delta Sungai Indragiri merupakan salah satu yang terluas di Sumatera. Masyarakat setempat memanfaatkan hasil hutan mangrove secara berkelanjutan termasuk arang, kayu bakar, dan perikanan.', spesies: ['Nypa fruticans', 'Rhizophora apiculata', 'Bruguiera parviflora', 'Xylocarpus moluccensis'], riwayat: [{ tanggal: '2024-05-15', aktivitas: 'Monitoring Pemanfaatan', detail: 'Evaluasi pemanfaatan lestari oleh masyarakat.' }] },
  { id: 'flora-012', name: 'Mangrove Mimika', category: 'flora', provinsi: 'Papua', kabupaten: 'Mimika', coords: [-4.55, 136.8], luas: '85.400 Ha', status: 'Kawasan Lindung', tev: 'Rp 2,5 T/thn', jumlahTitikPantau: 28, ringkasan: 'Mangrove pesisir selatan Papua dengan biodiversitas tinggi.', deskripsi: 'Kawasan mangrove Mimika di pesisir selatan Papua memiliki biodiversitas sangat tinggi dan relatif masih alami. Menjadi habitat penting bagi berbagai spesies endemik Papua.', spesies: ['Rhizophora stylosa', 'Avicennia alba', 'Sonneratia alba', 'Bruguiera gymnorrhiza', 'Ceriops tagal'], riwayat: [{ tanggal: '2023-12-10', aktivitas: 'Ekspedisi Ilmiah', detail: 'Penelitian kolaboratif dengan universitas internasional.' }] },

  // ═══════════ FAUNA ═══════════
  { id: 'fauna-001', name: 'Habitat Penyu Derawan', category: 'fauna', provinsi: 'Kalimantan Timur', kabupaten: 'Berau', coords: [2.28, 118.25], luas: '127.500 Ha', status: 'Kawasan Konservasi Perairan', tev: 'Rp 2,1 T/thn', jumlahTitikPantau: 18, ringkasan: 'Habitat peneluran penyu hijau dan penyu sisik utama di Indonesia.', deskripsi: 'Kepulauan Derawan merupakan salah satu habitat terpenting bagi penyu hijau (Chelonia mydas) dan penyu sisik (Eretmochelys imbricata) di Indonesia. Pulau Sangalaki menjadi lokasi peneluran utama dengan ratusan penyu bertelur setiap tahunnya.', spesies: ['Penyu Hijau', 'Penyu Sisik', 'Manta Ray', 'Pari Elang', 'Hiu Karang'], riwayat: [{ tanggal: '2024-03-15', aktivitas: 'Monitoring Peneluran', detail: 'Tercatat 342 induk penyu bertelur pada musim 2024.' }, { tanggal: '2024-06-20', aktivitas: 'Pelepasan Tukik', detail: 'Pelepasan 12.500 tukik ke laut.' }] },
  { id: 'fauna-002', name: 'Dugong Alor', category: 'fauna', provinsi: 'Nusa Tenggara Timur', kabupaten: 'Alor', coords: [-8.25, 124.75], luas: '45.000 Ha', status: 'Kawasan Konservasi', tev: 'Rp 320 M/thn', jumlahTitikPantau: 8, ringkasan: 'Habitat dugong dan padang lamun di perairan Alor.', deskripsi: 'Perairan Alor menjadi salah satu habitat dugong (Dugong dugon) yang tersisa di Indonesia timur. Padang lamun yang luas menjadi sumber pakan utama bagi mamalia laut yang dilindungi ini.', spesies: ['Dugong', 'Lumba-lumba Spinner', 'Penyu Hijau', 'Paus Pilot'], riwayat: [{ tanggal: '2024-02-10', aktivitas: 'Survei Populasi Dugong', detail: 'Estimasi populasi 15-20 individu di perairan Alor.' }] },
  { id: 'fauna-003', name: 'Terumbu Karang Bunaken', category: 'fauna', provinsi: 'Sulawesi Utara', kabupaten: 'Manado', coords: [1.62, 124.76], luas: '89.065 Ha', status: 'Taman Nasional', tev: 'Rp 1,5 T/thn', jumlahTitikPantau: 22, ringkasan: 'Taman nasional laut dengan keanekaragaman fauna laut terkaya.', deskripsi: 'Taman Nasional Bunaken memiliki dinding karang (wall reef) spektakuler dengan kedalaman mencapai 200 meter. Terdapat lebih dari 390 spesies karang dan ribuan spesies ikan karang yang menjadikannya surga bagi penyelam dunia.', spesies: ['Ikan Napoleon', 'Hiu Karang', 'Kuda Laut Pygmy', 'Ikan Mandarin', 'Nudibranch'], riwayat: [{ tanggal: '2024-01-20', aktivitas: 'Reef Check', detail: 'Pemantauan kesehatan terumbu karang di 15 stasiun.' }] },
  { id: 'fauna-004', name: 'Bekantan Balikpapan', category: 'fauna', provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', coords: [-1.25, 116.83], luas: '16.500 Ha', status: 'Kawasan Esensial', tev: 'Rp 480 M/thn', jumlahTitikPantau: 12, ringkasan: 'Habitat bekantan (proboscis monkey) di mangrove Teluk Balikpapan.', deskripsi: 'Kawasan mangrove Teluk Balikpapan merupakan habitat kritis bagi bekantan (Nasalis larvatus), primata endemik Kalimantan yang terancam punah. Populasi bekantan di sini diperkirakan sekitar 200-300 individu.', spesies: ['Bekantan', 'Kukang Kalimantan', 'Buaya Muara', 'Elang Laut'], riwayat: [{ tanggal: '2024-04-05', aktivitas: 'Sensus Bekantan', detail: 'Tercatat 245 individu di 8 lokasi pengamatan.' }] },
  { id: 'fauna-005', name: 'Paus Lamalera', category: 'fauna', provinsi: 'Nusa Tenggara Timur', kabupaten: 'Lembata', coords: [-8.35, 123.6], luas: '82.000 Ha', status: 'Kawasan Perairan Tradisional', tev: 'Rp 190 M/thn', jumlahTitikPantau: 6, ringkasan: 'Jalur migrasi paus dan lumba-lumba di selat Lembata.', deskripsi: 'Perairan Lamalera menjadi jalur migrasi berbagai spesies paus dan lumba-lumba. Masyarakat Lamalera memiliki tradisi berburu paus secara tradisional yang telah berlangsung selama ratusan tahun.', spesies: ['Paus Sperma', 'Paus Biru', 'Lumba-lumba Spinner', 'Ikan Pari Manta'], riwayat: [{ tanggal: '2024-05-01', aktivitas: 'Pengamatan Migrasi', detail: 'Tercatat 12 kelompok paus melewati perairan.' }] },
  { id: 'fauna-006', name: 'Hiu Paus Cenderawasih', category: 'fauna', provinsi: 'Papua', kabupaten: 'Nabire', coords: [-2.75, 134.85], luas: '1.453.500 Ha', status: 'Taman Nasional Laut', tev: 'Rp 3,8 T/thn', jumlahTitikPantau: 30, ringkasan: 'Habitat unik hiu paus yang berinteraksi dengan nelayan bagan.', deskripsi: 'Taman Nasional Teluk Cenderawasih terkenal dengan fenomena unik hiu paus (Rhincodon typus) yang berinteraksi dengan nelayan bagan. Merupakan taman nasional laut terbesar di Indonesia.', spesies: ['Hiu Paus', 'Penyu Belimbing', 'Ikan Napoleon', 'Duyung'], riwayat: [{ tanggal: '2024-07-10', aktivitas: 'Photo-ID Hiu Paus', detail: 'Teridentifikasi 48 individu hiu paus di database.' }] },
  { id: 'fauna-007', name: 'Orangutan Kutai', category: 'fauna', provinsi: 'Kalimantan Timur', kabupaten: 'Kutai Timur', coords: [0.35, 117.45], luas: '198.629 Ha', status: 'Taman Nasional', tev: 'Rp 1,2 T/thn', jumlahTitikPantau: 20, ringkasan: 'Habitat orangutan dan bekantan di hutan mangrove dan dipterocarp.', deskripsi: 'Taman Nasional Kutai merupakan perwakilan ekosistem hutan hujan tropis dataran rendah Kalimantan Timur yang menjadi habitat orangutan, bekantan, dan ribuan spesies flora-fauna lainnya.', spesies: ['Orangutan Kalimantan', 'Bekantan', 'Banteng', 'Macan Dahan'], riwayat: [{ tanggal: '2024-03-22', aktivitas: 'Sensus Orangutan', detail: 'Estimasi populasi 2.000 individu.' }] },
  { id: 'fauna-008', name: 'Badak Ujung Kulon', category: 'fauna', provinsi: 'Banten', kabupaten: 'Pandeglang', coords: [-6.75, 105.33], luas: '122.956 Ha', status: 'Taman Nasional / UNESCO', tev: 'Rp 2,4 T/thn', jumlahTitikPantau: 32, ringkasan: 'Habitat terakhir badak Jawa (Rhinoceros sondaicus).', deskripsi: 'Taman Nasional Ujung Kulon merupakan satu-satunya habitat alami badak Jawa yang tersisa di dunia. Populasi badak Jawa diperkirakan sekitar 80 individu. Kawasan ini juga melindungi ekosistem mangrove, terumbu karang, dan hutan tropis.', spesies: ['Badak Jawa', 'Banteng', 'Lutung Jawa', 'Owa Jawa', 'Elang Jawa'], riwayat: [{ tanggal: '2024-06-15', aktivitas: 'Monitoring Camera Trap', detail: 'Tercatat 82 individu badak dari 150 camera trap.' }] },
  { id: 'fauna-009', name: 'Komodo NTT', category: 'fauna', provinsi: 'Nusa Tenggara Timur', kabupaten: 'Manggarai Barat', coords: [-8.55, 119.48], luas: '173.300 Ha', status: 'Taman Nasional / UNESCO', tev: 'Rp 4,7 T/thn', jumlahTitikPantau: 26, ringkasan: 'Habitat komodo (Varanus komodoensis) satu-satunya di dunia.', deskripsi: 'Taman Nasional Komodo melindungi komodo, kadal terbesar di dunia, beserta ekosistem laut yang kaya. Perairan di sekitar pulau memiliki terumbu karang yang sangat sehat dan menjadi habitat bagi manta ray.', spesies: ['Komodo', 'Manta Ray', 'Penyu Hijau', 'Ikan Napoleon', 'Elang Flores'], riwayat: [{ tanggal: '2024-02-01', aktivitas: 'Sensus Komodo', detail: 'Populasi stabil di angka 3.300 individu.' }] },
  { id: 'fauna-010', name: 'Maleo Bogani', category: 'fauna', provinsi: 'Sulawesi Utara', kabupaten: 'Bolaang Mongondow', coords: [0.55, 124.0], luas: '287.115 Ha', status: 'Taman Nasional', tev: 'Rp 890 M/thn', jumlahTitikPantau: 16, ringkasan: 'Habitat burung maleo dan anoa di hutan Bogani Nani Wartabone.', deskripsi: 'Taman Nasional Bogani Nani Wartabone melindungi keanekaragaman fauna endemik Sulawesi termasuk burung maleo, anoa, dan tarsius. Kawasan ini memiliki ekosistem hutan hujan tropis pegunungan yang masih alami.', spesies: ['Maleo', 'Anoa', 'Tarsius Sulawesi', 'Kuskus Beruang'], riwayat: [{ tanggal: '2024-04-18', aktivitas: 'Monitoring Sarang Maleo', detail: 'Tercatat 120 sarang aktif di 5 lokasi.' }] },

  // ═══════════ PERIKANAN TANGKAP ═══════════
  { id: 'tangkap-001', name: 'WPP 713 Selat Makassar', category: 'tangkap', provinsi: 'Kalimantan-Sulawesi', kabupaten: 'Lintas Provinsi', coords: [-3.5, 118.0], luas: 'WPP 713', status: 'Zona Penangkapan Utama', tev: 'Rp 8,2 T/thn', jumlahTitikPantau: 28, ringkasan: 'Zona penangkapan utama tuna, cakalang, dan tongkol.', deskripsi: 'WPP 713 (Selat Makassar dan Laut Flores) merupakan salah satu wilayah penangkapan ikan paling produktif di Indonesia. Kaya akan ikan pelagis besar seperti tuna, cakalang, dan tongkol yang menjadi komoditas ekspor utama.', spesies: ['Tuna Sirip Kuning', 'Cakalang', 'Tongkol', 'Tenggiri', 'Layang'], riwayat: [{ tanggal: '2024-01-10', aktivitas: 'Survei Stok Ikan', detail: 'Estimasi stok tuna masih dalam batas berkelanjutan.' }] },
  { id: 'tangkap-002', name: 'WPP 718 Laut Arafura', category: 'tangkap', provinsi: 'Papua', kabupaten: 'Merauke', coords: [-7.5, 135.0], luas: 'WPP 718', status: 'Zona Penangkapan Utama', tev: 'Rp 12,3 T/thn', jumlahTitikPantau: 22, ringkasan: 'Wilayah penangkapan terkaya untuk udang dan ikan demersal.', deskripsi: 'Laut Arafura merupakan wilayah perikanan paling produktif di Indonesia, khususnya untuk udang dan ikan demersal. Hasil tangkapan dari wilayah ini memiliki nilai ekonomi tertinggi secara nasional.', spesies: ['Udang Windu', 'Udang Jerbung', 'Kakap Merah', 'Bawal', 'Kerapu'], riwayat: [{ tanggal: '2024-03-05', aktivitas: 'Pengawasan IUU Fishing', detail: 'Operasi pengawasan terhadap kapal ilegal.' }] },
  { id: 'tangkap-003', name: 'WPP 712 Laut Jawa', category: 'tangkap', provinsi: 'Jawa', kabupaten: 'Lintas Provinsi', coords: [-6.0, 112.0], luas: 'WPP 712', status: 'Zona Penangkapan Tradisional', tev: 'Rp 5,6 T/thn', jumlahTitikPantau: 32, ringkasan: 'Zona penangkapan tradisional pantai utara Jawa.', deskripsi: 'Laut Jawa merupakan wilayah penangkapan tradisional bagi nelayan dari pesisir utara Jawa. Komoditas utama meliputi rajungan, ikan demersal, dan ikan pelagis kecil. Banyak nelayan menggunakan alat tangkap tradisional.', spesies: ['Rajungan', 'Tongkol', 'Layang', 'Kembung', 'Cumi-cumi'], riwayat: [{ tanggal: '2024-02-20', aktivitas: 'Pendataan Nelayan', detail: 'Tercatat 45.000 nelayan aktif di pesisir utara Jawa.' }] },
  { id: 'tangkap-004', name: 'WPP 714 Laut Banda', category: 'tangkap', provinsi: 'Maluku', kabupaten: 'Maluku Tengah', coords: [-5.0, 129.5], luas: 'WPP 714', status: 'Zona Penangkapan', tev: 'Rp 4,5 T/thn', jumlahTitikPantau: 14, ringkasan: 'Perairan dalam kaya ikan pelagis besar.', deskripsi: 'Laut Banda merupakan perairan dalam yang kaya akan ikan pelagis besar. Secara historis, kepulauan Banda terkenal sebagai pusat perdagangan rempah-rempah dan kini menjadi zona perikanan penting.', spesies: ['Tuna Mata Besar', 'Marlin', 'Ikan Layaran', 'Cakalang'], riwayat: [{ tanggal: '2024-04-12', aktivitas: 'Monitoring Hasil Tangkapan', detail: 'Produksi tuna meningkat 12% dari tahun sebelumnya.' }] },
  { id: 'tangkap-005', name: 'WPP 711 Selat Karimata', category: 'tangkap', provinsi: 'Kalimantan Barat', kabupaten: 'Ketapang', coords: [-2.0, 108.5], luas: 'WPP 711', status: 'Zona Penangkapan', tev: 'Rp 3,8 T/thn', jumlahTitikPantau: 16, ringkasan: 'Zona penangkapan ikan pelagis kecil dan udang.', deskripsi: 'Selat Karimata dan Laut Natuna Selatan merupakan wilayah penangkapan yang produktif untuk ikan pelagis kecil. Nelayan dari berbagai daerah beroperasi di perairan ini.', spesies: ['Kembung', 'Layang', 'Selar', 'Teri', 'Udang Jerbung'], riwayat: [{ tanggal: '2024-05-08', aktivitas: 'Survei Hidro-akustik', detail: 'Estimasi biomassa ikan pelagis kecil 850.000 ton.' }] },
  { id: 'tangkap-006', name: 'WPP 715 Teluk Tomini', category: 'tangkap', provinsi: 'Sulawesi Tengah', kabupaten: 'Poso', coords: [-0.5, 121.5], luas: 'WPP 715', status: 'Zona Penangkapan', tev: 'Rp 2,1 T/thn', jumlahTitikPantau: 10, ringkasan: 'Zona penangkapan ikan pelagis di Teluk Tomini.', deskripsi: 'Teluk Tomini merupakan teluk terbesar di Sulawesi dengan potensi perikanan yang besar. Ikan tuna dan cakalang menjadi komoditas utama yang ditangkap oleh nelayan lokal.', spesies: ['Cakalang', 'Tongkol', 'Tuna Sirip Kuning', 'Layang'], riwayat: [{ tanggal: '2024-06-01', aktivitas: 'Pelatihan Nelayan', detail: 'Pelatihan teknik penangkapan berkelanjutan untuk 200 nelayan.' }] },
  { id: 'tangkap-007', name: 'WPP 716 Laut Sulawesi', category: 'tangkap', provinsi: 'Sulawesi Utara', kabupaten: 'Bitung', coords: [2.0, 125.5], luas: 'WPP 716', status: 'Zona Penangkapan', tev: 'Rp 5,4 T/thn', jumlahTitikPantau: 18, ringkasan: 'Sentra perikanan tuna Sulawesi Utara.', deskripsi: 'Laut Sulawesi merupakan sentra perikanan tuna terbesar di Indonesia. Kota Bitung menjadi pusat industri pengolahan tuna dengan ekspor ke berbagai negara.', spesies: ['Tuna Sirip Kuning', 'Tuna Mata Besar', 'Cakalang', 'Marlin'], riwayat: [{ tanggal: '2024-01-30', aktivitas: 'Sertifikasi MSC', detail: 'Proses sertifikasi perikanan berkelanjutan.' }] },

  // ═══════════ PERIKANAN BUDIDAYA ═══════════
  { id: 'budidaya-001', name: 'Sentra Udang Lampung', category: 'budidaya', provinsi: 'Lampung', kabupaten: 'Lampung Selatan', coords: [-5.45, 105.26], luas: '45.200 Ha', status: 'Sentra Budidaya Udang', tev: 'Rp 6,8 T/thn', jumlahTitikPantau: 24, ringkasan: 'Sentra budidaya udang vaname terbesar di Sumatera.', deskripsi: 'Lampung merupakan salah satu sentra budidaya udang vaname terbesar di Indonesia. Dengan teknologi intensif dan semi-intensif, produksi udang dari Lampung menjadi tulang punggung ekspor udang nasional.', spesies: ['Udang Vaname', 'Udang Windu', 'Bandeng'], riwayat: [{ tanggal: '2024-02-15', aktivitas: 'Monitoring Kualitas Air', detail: 'Pemantauan parameter kualitas air di 120 tambak.' }, { tanggal: '2024-05-10', aktivitas: 'Panen Raya', detail: 'Total produksi 2.400 ton udang vaname.' }] },
  { id: 'budidaya-002', name: 'Rumput Laut Nusa Penida', category: 'budidaya', provinsi: 'Bali', kabupaten: 'Klungkung', coords: [-8.73, 115.54], luas: '12.800 Ha', status: 'Sentra Budidaya Rumput Laut', tev: 'Rp 890 M/thn', jumlahTitikPantau: 14, ringkasan: 'Sentra budidaya rumput laut Eucheuma di Bali.', deskripsi: 'Perairan Nusa Penida dan Nusa Lembongan menjadi sentra budidaya rumput laut jenis Eucheuma cottonii. Budidaya rumput laut menjadi mata pencaharian utama masyarakat pesisir di kawasan ini.', spesies: ['Eucheuma cottonii', 'Gracilaria sp.', 'Kappaphycus alvarezii'], riwayat: [{ tanggal: '2024-03-20', aktivitas: 'Distribusi Bibit Unggul', detail: 'Distribusi 5 ton bibit rumput laut unggul.' }] },
  { id: 'budidaya-003', name: 'Tambak Takalar', category: 'budidaya', provinsi: 'Sulawesi Selatan', kabupaten: 'Takalar', coords: [-5.42, 119.45], luas: '32.500 Ha', status: 'Sentra Budidaya', tev: 'Rp 4,2 T/thn', jumlahTitikPantau: 20, ringkasan: 'Sentra budidaya udang dan bandeng Sulawesi Selatan.', deskripsi: 'Kabupaten Takalar merupakan sentra utama budidaya udang dan bandeng di Sulawesi Selatan. Dengan dukungan iklim dan topografi yang ideal, produktivitas tambak di wilayah ini tergolong tinggi.', spesies: ['Udang Vaname', 'Bandeng', 'Kepiting Bakau'], riwayat: [{ tanggal: '2024-04-25', aktivitas: 'Pelatihan Budidaya', detail: 'Pelatihan teknologi budidaya untuk 150 petambak.' }] },
  { id: 'budidaya-004', name: 'Mutiara Lombok', category: 'budidaya', provinsi: 'Nusa Tenggara Barat', kabupaten: 'Lombok Utara', coords: [-8.35, 116.15], luas: '8.600 Ha', status: 'Sentra Budidaya Mutiara', tev: 'Rp 1,2 T/thn', jumlahTitikPantau: 10, ringkasan: 'Sentra budidaya mutiara Pinctada maxima terbesar.', deskripsi: 'Perairan Lombok Utara menjadi lokasi budidaya mutiara laut selatan (Pinctada maxima) terbesar di Indonesia. Mutiara Lombok dikenal di pasar internasional dengan kualitas premium.', spesies: ['Pinctada maxima', 'Lobster Mutiara'], riwayat: [{ tanggal: '2024-06-05', aktivitas: 'Panen Mutiara', detail: 'Panen 50.000 butir mutiara dengan grade AAA 15%.' }] },
  { id: 'budidaya-005', name: 'Kerapu Situbondo', category: 'budidaya', provinsi: 'Jawa Timur', kabupaten: 'Situbondo', coords: [-7.7, 114.0], luas: '5.400 Ha', status: 'Sentra Budidaya Kerapu', tev: 'Rp 780 M/thn', jumlahTitikPantau: 8, ringkasan: 'Sentra pembenihan dan budidaya kerapu di Jawa Timur.', deskripsi: 'Situbondo menjadi pusat pembenihan dan budidaya kerapu terbesar di Jawa Timur. Balai Besar Perikanan Budidaya Laut (BBPBL) di sini menjadi rujukan nasional untuk teknologi budidaya kerapu.', spesies: ['Kerapu Tikus', 'Kerapu Cantang', 'Kerapu Macan'], riwayat: [{ tanggal: '2024-01-18', aktivitas: 'Produksi Benih', detail: 'Produksi 2 juta benih kerapu untuk distribusi nasional.' }] },
  { id: 'budidaya-006', name: 'Bandeng Gresik', category: 'budidaya', provinsi: 'Jawa Timur', kabupaten: 'Gresik', coords: [-7.16, 112.65], luas: '18.200 Ha', status: 'Sentra Budidaya Bandeng', tev: 'Rp 1,5 T/thn', jumlahTitikPantau: 16, ringkasan: 'Sentra budidaya bandeng terbesar di Indonesia.', deskripsi: 'Gresik dan sekitarnya merupakan sentra budidaya bandeng terbesar di Indonesia. Tambak-tambak tradisional dan semi-intensif menghasilkan bandeng yang dipasarkan ke seluruh Jawa dan Bali.', spesies: ['Bandeng', 'Udang Windu', 'Rumput Laut'], riwayat: [{ tanggal: '2024-05-20', aktivitas: 'Festival Bandeng', detail: 'Festival tahunan dengan lomba bandeng terbesar.' }] },
  { id: 'budidaya-007', name: 'Lobster Sumbawa', category: 'budidaya', provinsi: 'Nusa Tenggara Barat', kabupaten: 'Sumbawa', coords: [-8.5, 117.42], luas: '6.400 Ha', status: 'Sentra Budidaya Lobster', tev: 'Rp 920 M/thn', jumlahTitikPantau: 8, ringkasan: 'Kawasan budidaya lobster air laut dengan teknik keramba.', deskripsi: 'Perairan Sumbawa menjadi lokasi potensial untuk budidaya lobster (Panulirus sp.) menggunakan sistem keramba jaring apung. Pemerintah mendukung pengembangan budidaya lobster sebagai komoditas ekspor bernilai tinggi.', spesies: ['Lobster Pasir', 'Lobster Mutiara', 'Lobster Bambu'], riwayat: [{ tanggal: '2024-07-01', aktivitas: 'Uji Coba KJA', detail: 'Uji coba keramba jaring apung untuk 10.000 ekor lobster.' }] },
  { id: 'budidaya-008', name: 'Rumput Laut Buton', category: 'budidaya', provinsi: 'Sulawesi Tenggara', kabupaten: 'Buton', coords: [-5.3, 122.9], luas: '18.700 Ha', status: 'Sentra Budidaya Rumput Laut', tev: 'Rp 760 M/thn', jumlahTitikPantau: 12, ringkasan: 'Sentra produksi rumput laut di Sulawesi Tenggara.', deskripsi: 'Kepulauan Buton dan sekitarnya merupakan sentra produksi rumput laut terbesar di Sulawesi Tenggara. Rumput laut diolah menjadi karaginan untuk industri makanan dan kosmetik.', spesies: ['Kappaphycus alvarezii', 'Eucheuma denticulatum'], riwayat: [{ tanggal: '2024-04-15', aktivitas: 'Panen Rumput Laut', detail: 'Total produksi mencapai 8.500 ton kering.' }] },

  // ═══════════ PESISIR LAUT ═══════════
  { id: 'pesisir-001', name: 'Pesisir Raja Ampat', category: 'pesisir', provinsi: 'Papua Barat', kabupaten: 'Raja Ampat', coords: [-1.0, 131.0], luas: '1.508.000 Ha', status: 'Kawasan Konservasi Perairan', tev: 'Rp 6,1 T/thn', jumlahTitikPantau: 42, ringkasan: 'Kawasan konservasi perairan dengan biodiversitas laut tertinggi di dunia.', deskripsi: 'Raja Ampat merupakan episentrum keanekaragaman hayati laut dunia (Coral Triangle). Dengan lebih dari 1.500 spesies ikan dan 600 spesies karang keras, kawasan ini menjadi destinasi selam kelas dunia sekaligus area konservasi prioritas global.', spesies: ['Karang Keras (600+ sp.)', 'Ikan Karang (1.500+ sp.)', 'Manta Ray', 'Hiu Karang'], riwayat: [{ tanggal: '2024-01-05', aktivitas: 'Marine Rapid Assessment', detail: 'Survei biodiversitas komprehensif di 25 stasiun.' }, { tanggal: '2024-06-15', aktivitas: 'Pelatihan Sasi Laut', detail: 'Penguatan kearifan lokal sasi untuk pengelolaan perikanan.' }] },
  { id: 'pesisir-002', name: 'Pesisir Wakatobi', category: 'pesisir', provinsi: 'Sulawesi Tenggara', kabupaten: 'Wakatobi', coords: [-5.45, 122.17], luas: '1.390.000 Ha', status: 'Taman Nasional', tev: 'Rp 3,2 T/thn', jumlahTitikPantau: 28, ringkasan: 'Taman nasional laut dengan atol karang terbesar kedua di dunia.', deskripsi: 'Taman Nasional Wakatobi terdiri dari empat pulau utama (Wangi-Wangi, Kaledupa, Tomia, Binongko) dengan sistem atol karang yang spektakuler. Menjadi Cagar Biosfer UNESCO sejak 2012.', spesies: ['Karang Keras (396 sp.)', 'Ikan Karang (590 sp.)', 'Penyu Sisik', 'Lumba-lumba'], riwayat: [{ tanggal: '2024-02-28', aktivitas: 'Monitoring Bleaching', detail: 'Pemantauan dampak El Nino terhadap karang.' }] },
  { id: 'pesisir-003', name: 'Pesisir Karimunjawa', category: 'pesisir', provinsi: 'Jawa Tengah', kabupaten: 'Jepara', coords: [-5.87, 110.44], luas: '111.625 Ha', status: 'Taman Nasional', tev: 'Rp 1,3 T/thn', jumlahTitikPantau: 18, ringkasan: 'Taman nasional kepulauan dengan terumbu karang dan mangrove.', deskripsi: 'Taman Nasional Karimunjawa terdiri dari 27 pulau dengan keanekaragaman ekosistem laut yang tinggi. Kawasan ini menawarkan pengalaman wisata bahari mulai dari snorkeling, diving, hingga tracking mangrove.', spesies: ['Karang Keras (90 genus)', 'Ikan Karang (242 sp.)', 'Hiu Karang', 'Penyu Hijau'], riwayat: [{ tanggal: '2024-03-10', aktivitas: 'Transplantasi Karang', detail: 'Transplantasi 5.000 fragmen karang di 3 lokasi.' }] },
  { id: 'pesisir-004', name: 'Pesisir Kepulauan Seribu', category: 'pesisir', provinsi: 'DKI Jakarta', kabupaten: 'Kep. Seribu', coords: [-5.72, 106.56], luas: '107.489 Ha', status: 'Taman Nasional', tev: 'Rp 1,8 T/thn', jumlahTitikPantau: 22, ringkasan: 'Taman nasional laut terdekat dari ibu kota Jakarta.', deskripsi: 'Taman Nasional Kepulauan Seribu merupakan kawasan konservasi laut yang terdekat dari ibu kota Jakarta. Meskipun menghadapi tekanan dari aktivitas perkotaan, upaya konservasi dan rehabilitasi terumbu karang terus dilakukan.', spesies: ['Karang Keras (144 sp.)', 'Ikan Karang (225 sp.)', 'Penyu Sisik', 'Kima'], riwayat: [{ tanggal: '2024-04-22', aktivitas: 'Hari Bumi - Tanam Karang', detail: 'Penanaman 2.000 fragmen karang oleh relawan.' }] },
  { id: 'pesisir-005', name: 'Pesisir Nusa Penida', category: 'pesisir', provinsi: 'Bali', kabupaten: 'Klungkung', coords: [-8.73, 115.54], luas: '20.057 Ha', status: 'Kawasan Konservasi Perairan', tev: 'Rp 1,1 T/thn', jumlahTitikPantau: 16, ringkasan: 'Kawasan konservasi perairan dengan habitat manta ray.', deskripsi: 'Kawasan konservasi perairan Nusa Penida terkenal sebagai habitat manta ray (Mobula alfredi) dan mola-mola (Mola mola). Arus yang kuat membawa nutrien dari laut dalam, menciptakan perairan yang kaya biodiversitas.', spesies: ['Manta Ray', 'Mola-mola', 'Hiu Karang', 'Penyu Hijau'], riwayat: [{ tanggal: '2024-05-30', aktivitas: 'Manta Census', detail: 'Teridentifikasi 420 individu manta dari photo-ID.' }] },
  { id: 'pesisir-006', name: 'Pesisir Banda Neira', category: 'pesisir', provinsi: 'Maluku', kabupaten: 'Maluku Tengah', coords: [-4.52, 129.9], luas: '24.800 Ha', status: 'Kawasan Wisata Bahari', tev: 'Rp 450 M/thn', jumlahTitikPantau: 10, ringkasan: 'Perairan bersejarah dengan terumbu karang dan gunung api bawah laut.', deskripsi: 'Kepulauan Banda memiliki sejarah panjang sebagai pusat perdagangan pala. Perairan di sekitarnya memiliki terumbu karang yang masih sangat sehat dengan biodiversitas tinggi, serta fenomena geologi gunung api bawah laut aktif.', spesies: ['Karang Keras (310 sp.)', 'Hiu Karang', 'Ikan Napoleon', 'Barrakuda'], riwayat: [{ tanggal: '2024-07-05', aktivitas: 'Survei Geologi Bawah Laut', detail: 'Pemetaan struktur gunung api Banda Api bawah laut.' }] },
  { id: 'pesisir-007', name: 'Pesisir Morotai', category: 'pesisir', provinsi: 'Maluku Utara', kabupaten: 'Pulau Morotai', coords: [2.3, 128.4], luas: '56.000 Ha', status: 'KEK Pariwisata', tev: 'Rp 680 M/thn', jumlahTitikPantau: 8, ringkasan: 'Kawasan ekonomi khusus pariwisata dengan potensi wisata bahari.', deskripsi: 'Pulau Morotai ditetapkan sebagai Kawasan Ekonomi Khusus (KEK) Pariwisata. Memiliki pantai berpasir putih, terumbu karang yang masih alami, serta situs sejarah Perang Dunia II yang menjadi daya tarik unik.', spesies: ['Karang Keras', 'Ikan Pelagis', 'Penyu Hijau', 'Lumba-lumba'], riwayat: [{ tanggal: '2024-06-28', aktivitas: 'Pengembangan Wisata Selam', detail: 'Pembukaan 5 dive site baru untuk wisata selam.' }] },
  { id: 'pesisir-008', name: 'Pesisir Togean', category: 'pesisir', provinsi: 'Sulawesi Tengah', kabupaten: 'Tojo Una-Una', coords: [-0.42, 122.0], luas: '362.605 Ha', status: 'Taman Nasional', tev: 'Rp 1,6 T/thn', jumlahTitikPantau: 20, ringkasan: 'Taman nasional kepulauan dengan ekosistem terumbu karang unik.', deskripsi: 'Taman Nasional Kepulauan Togean memiliki semua tipe terumbu karang utama: karang tepi, karang penghalang, karang atol, dan karang tompok. Termasuk salah satu taman nasional laut paling terpencil dan masih alami di Indonesia.', spesies: ['Karang Keras (262 sp.)', 'Ikan Karang (596 sp.)', 'Kima', 'Nautilus'], riwayat: [{ tanggal: '2024-08-01', aktivitas: 'Penelitian Atol', detail: 'Dokumentasi formasi atol langka Una-Una.' }] },
  { id: 'pesisir-009', name: 'Pesisir Sawu', category: 'pesisir', provinsi: 'Nusa Tenggara Timur', kabupaten: 'Sabu Raijua', coords: [-10.5, 122.0], luas: '3.521.130 Ha', status: 'Taman Nasional Perairan', tev: 'Rp 2,8 T/thn', jumlahTitikPantau: 14, ringkasan: 'Taman nasional perairan terbesar untuk jalur migrasi cetacea.', deskripsi: 'Taman Nasional Perairan Laut Sawu merupakan kawasan konservasi laut terbesar di Indonesia. Laut Sawu menjadi jalur migrasi penting bagi 30 spesies paus dan lumba-lumba, serta habitat penyu belimbing.', spesies: ['Paus Biru', 'Paus Sperma', 'Lumba-lumba', 'Penyu Belimbing', 'Manta Ray'], riwayat: [{ tanggal: '2024-03-18', aktivitas: 'Survei Cetacea', detail: 'Tercatat 22 spesies cetacea dalam survei 30 hari.' }] },
  { id: 'pesisir-010', name: 'Pesisir Tanjung Puting', category: 'pesisir', provinsi: 'Kalimantan Tengah', kabupaten: 'Kotawaringin Barat', coords: [-2.75, 111.65], luas: '415.040 Ha', status: 'Taman Nasional', tev: 'Rp 1,9 T/thn', jumlahTitikPantau: 18, ringkasan: 'Taman nasional dengan ekosistem mangrove, rawa gambut, dan pesisir.', deskripsi: 'Taman Nasional Tanjung Puting terkenal sebagai habitat orangutan Kalimantan dan memiliki kawasan pesisir dengan ekosistem mangrove yang luas. Sungai-sungai di taman nasional ini menjadi jalur wisata klotok yang populer.', spesies: ['Orangutan', 'Bekantan', 'Buaya Muara', 'Pesut Mahakam'], riwayat: [{ tanggal: '2024-02-14', aktivitas: 'Monitoring Pesisir', detail: 'Pemantauan kondisi mangrove dan abrasi pantai.' }] },
];

// ── Helper Functions ──
export function getLocationById(id) {
  return locations.find((loc) => loc.id === id);
}

export function getLocationsByCategory(catId) {
  return locations.filter((loc) => loc.category === catId);
}

export function getCategoryInfo(catId) {
  return categories.find((c) => c.id === catId);
}

export function getLocationsByProvince(province) {
  return locations.filter((loc) => loc.provinsi === province);
}
